# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ece87df74614899876abbc5949c051eef55423eea6afbbfbe5ef90dd430c90f801bc91cc3f245a35266f940275e2ded3a231d85ef0bf18a8c2ec7af6a6fc8009

test:
  secret_key_base: 667975c0a3232ff31e811ea637cb821b82335d0ddaf1f5010515535bcf526f3d702b7b2e033bef504818f83c966a0c1109e0eeb1fba1010be858b17a9bc86a1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
